# API Info
spring.application.name=Banking App

# Server
server.port=8080

# -------------------------------------------------------
# DATABASE — PostgreSQL (active when Docker is running)
# -------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5434/bankingdb
spring.datasource.username=banking_user
spring.datasource.password=banking_pass

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.tryItOutEnabled=true

# JWT
jwt.secret=banking-app-secret-key-must-be-at-least-256-bits-long
jwt.expiration=86400000


# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=false

# HikariCP Connection Pool
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.pool-name=BankingHikariPool
spring.datasource.hikari.leak-detection-threshold=60000

# ── Kafka ────────────────────────────────────────────────────────────────────

# Where Kafka is running — matches the port in docker-compose.yml
spring.kafka.bootstrap-servers=localhost:9092

# Producer — how to convert Java objects to bytes before sending to Kafka
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Consumer — which group this app belongs to
# All consumers in the same group share the work — only one of them reads each message
spring.kafka.consumer.group-id=banking-audit-group

# latest = only read NEW messages after app starts
# earliest = replay all messages from beginning (useful for reprocessing)
spring.kafka.consumer.auto-offset-reset=latest

# Consumer — how to convert bytes back to Java objects after receiving from Kafka
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# Security — only trust our own package when deserializing JSON back to Java objects
# Without this Kafka refuses to deserialize for security reasons
spring.kafka.consumer.properties.spring.json.trusted.packages=com.banking.kafka